let bookData = [
  {
    id: "b1",
    category: ["featuredbook"],
    link: "https://bookland.dexignzone.com/xhtml/images/books/large/bigbook1.jpg",
    title: "A Heavy Lift",
    author: "Alan Walker",
    genre: "Business & Strategy",
    des: "The book is a practical guide to developing a winning business strategy. With real-world examples and actionable advice, this book covers essential elements for success in today's competitive business landscape.",
    price: "9.5",
    oldPrice: "12.0",
    discount: "20%",
  },
  {
    id: "b2",
    category: ["featuredbook", "bestseller"],
    link: "https://bookland.dexignzone.com/xhtml/images/books/large/bigbook2.jpg",
    title: "Pushing Clouds",
    author: "Nexus Block",
    genre: "Adventure, Science, Comedy",
    des: "The book is a practical guide to developing a winning business strategy. With real-world examples and actionable advice, this book covers essential elements for success in today's competitive business landscape.",
    price: "45.25",
    oldPrice: "60.00",
    discount: "20%",
  },

  {
    id: "b3",
    category: ["featuredbook", "bestseller"],
    link: "https://bookland.dexignzone.com/xhtml/images/books/book16.png",
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    genre: "Business & Strategy",
    des: "The book is a practical guide to developing a winning business strategy. With real-world examples and actionable advice, this book covers essential elements for success in today's competitive business landscape.",
    price: "25.25",
    oldPrice: "30.00",
    discount: "20%",
  },
  {
    id: "bos1",
    category: ["bookonsale"],
    discount: "50%",
    link: "https://bookland.dexignzone.com/xhtml/images/books/grid/book11.jpg",
    title: "All Good News",
    genre: "BUSINESS, STRATEGY",
    rating: "4.7",
    oldPrice: "98.4",
    newPrice: "45.4",
  },
  {
    id: "bos2",
    discount: "45%",
    category: ["bookonsale"],
    link: "https://bookland.dexignzone.com/xhtml/images/books/grid/book5.jpg",
    title: "Take Out Tango",
    genre: "SPORT, DRAMMA",
    rating: "4.5",
    oldPrice: "80.2",
    newPrice: "45.5",
  },
  {
    id: "bos3",
    discount: "50%",
    category: ["bookonsale"],
    link: "https://bookland.dexignzone.com/xhtml/images/books/grid/book3.jpg",
    title: "Battle Drive",
    genre: "SPORT, DRAMMA",
    rating: "4.3",
    oldPrice: "80.4",
    newPrice: "40.2",
  },
  {
    id: "bos4",
    discount: "30%",
    category: ["bookonsale"],
    link: "https://bookland.dexignzone.com/xhtml/images/books/grid/book7.jpg",
    title: "Seconds [PART 1]",
    genre: "HORROR, PLOT TWIST",
    rating: "4.9",
    oldPrice: "98.4",
    newPrice: "76.1",
  },
  {
    id: "bos5",
    discount: "25%",
    category: ["bookonsale"],
    link: "https://bookland.dexignzone.com/xhtml/images/books/grid/book15.jpg",
    title: "Terrible Madness",
    genre: "ADVENTURE, ACTION",
    rating: "3.9",
    oldPrice: "60.4",
    newPrice: "42.1",
  },
  {
    id: "bos6",
    discount: "50%",
    category: ["bookonsale"],
    link: "https://bookland.dexignzone.com/xhtml/images/books/grid/book12.jpg",
    title: "The Missadventure",
    genre: "ADVENTURE, SURVIVAL",
    rating: "4.7",
    oldPrice: "98.4",
    newPrice: "45.4",
  },
  {
    id: "bos7",
    discount: "50%",
    category: ["bookonsale"],
    link: "https://bookland.dexignzone.com/xhtml/images/books/grid/book3.jpg",
    title: "Battle Drive",
    genre: "SPORT, DRAMMA",
    rating: "4.3",
    oldPrice: "80.4",
    newPrice: "40.2",
  },
  {
    id: "bos8",
    discount: "30%",
    category: ["bookonsale"],
    link: "https://bookland.dexignzone.com/xhtml/images/books/grid/book7.jpg",
    title: "Seconds [PART 1]",
    genre: "HORROR, PLOT TWIST",
    rating: "4.9",
    oldPrice: "98.4",
    newPrice: "76.1",
  },
  {
    id: "bos9",
    discount: "50%",
    category: ["bookonsale"],
    link: "https://bookland.dexignzone.com/xhtml/images/books/grid/book11.jpg",
    title: "All Good News",
    genre: "BUSINESS, STRATEGY",
    rating: "4.7",
    oldPrice: "98.4",
    newPrice: "45.4",
  },
  {
    id: "bos10",
    discount: "45%",
    category: ["bookonsale"],
    link: "https://bookland.dexignzone.com/xhtml/images/books/grid/book5.jpg",
    title: "Take Out Tango",
    genre: "SPORT, DRAMMA",
    rating: "4.5",
    oldPrice: "80.2",
    newPrice: "45.5",
  },
  {
    id: "bos11",
    discount: "30%",
    category: ["bookonsale"],
    link: "https://bookland.dexignzone.com/xhtml/images/books/grid/book7.jpg",
    title: "Seconds [PART 1]",
    genre: "HORROR, PLOT TWIST",
    rating: "4.9",
    oldPrice: "98.4",
    newPrice: "76.1",
  },
  {
    id: "bos12",
    discount: "25%",
    category: ["bookonsale"],
    link: "https://bookland.dexignzone.com/xhtml/images/books/grid/book15.jpg",
    title: "Terrible Madness",
    genre: "ADVENTURE, ACTION",
    rating: "3.9",
    oldPrice: "60.4",
    newPrice: "42.1",
  },
  {
    id: "bos13",
    discount: "50%",
    category: ["bookonsale"],
    link: "https://bookland.dexignzone.com/xhtml/images/books/grid/book12.jpg",
    title: "The Missadventure",
    genre: "ADVENTURE, SURVIVAL",
    rating: "4.7",
    oldPrice: "98.4",
    newPrice: "45.4",
  },
  {
    id: "bos14",
    discount: "50%",
    category: ["bookonsale"],
    link: "https://bookland.dexignzone.com/xhtml/images/books/grid/book3.jpg",
    title: "Battle Drive",
    genre: "SPORT, DRAMMA",
    rating: "4.3",
    oldPrice: "80.4",
    newPrice: "40.2",
  },
  {
    id: "bos15",
    discount: "45%",
    category: ["bookonsale"],
    link: "https://bookland.dexignzone.com/xhtml/images/books/grid/book5.jpg",
    title: "Take Out Tango",
    genre: "SPORT, DRAMMA",
    rating: "4.5",
    oldPrice: "80.2",
    newPrice: "45.5",
  },
];
export default bookData;
