let users = [
  {
    id: "idd4740f0662fdf",
    ava: "https://icon-library.com/images/default-user-icon/default-user-icon-13.jpg",
    email: "abc@gmail.com",
    username: "User",
    password: "123456",
    cart: [
      {
        id: "b1",
        category: ["featuredbook"],
        link: "https://bookland.dexignzone.com/xhtml/images/books/large/bigbook1.jpg",
        title: "A Heavy Lift",
        author: "Alan Walker",
        genre: "Business & Strategy",
        des: "The book is a practical guide to developing a winning business strategy. With real-world examples and actionable advice, this book covers essential elements for success in today's competitive business landscape.",
        price: "9.5",
        oldPrice: "12.0",
        discount: "20",
        quantity: "1",
      },
      {
        id: "b2",
        category: ["featuredbook", "bestseller"],
        link: "https://bookland.dexignzone.com/xhtml/images/books/large/bigbook2.jpg",
        title: "Pushing Clouds",
        author: "Nexus Block",
        genre: "Adventure, Science, Comedy",
        des: "The book is a practical guide to developing a winning business strategy. With real-world examples and actionable advice, this book covers essential elements for success in today's competitive business landscape.",
        price: "45.25",
        oldPrice: "60.00",
        discount: "20",
        star: 4,
        quantity: "2",
      },
    ],
    orders: [
      {
        id: "lj87rnfp1pp9yd7n8p5",
        order: [
          {
            id: "b1",
            category: ["featuredbook"],
            link: "https://bookland.dexignzone.com/xhtml/images/books/large/bigbook1.jpg",
            title: "A Heavy Lift",
            author: "Alan Walker",
            genre: "Business & Strategy",
            des: "The book is a practical guide to developing a winning business strategy. With real-world examples and actionable advice, this book covers essential elements for success in today's competitive business landscape.",
            price: "9.5",
            oldPrice: "12.0",
            discount: "20",
            quantity: "1",
          },
          {
            id: "b2",
            category: ["featuredbook", "bestseller"],
            link: "https://bookland.dexignzone.com/xhtml/images/books/large/bigbook2.jpg",
            title: "Pushing Clouds",
            author: "Nexus Block",
            genre: "Adventure, Science, Comedy",
            des: "The book is a practical guide to developing a winning business strategy. With real-world examples and actionable advice, this book covers essential elements for success in today's competitive business landscape.",
            price: "45.25",
            oldPrice: "60.00",
            discount: "20",
            star: 4,
            quantity: "2",
          },
        ],
        time: "5:00 20/6/2023",
        receiver: "Anakin",
        address: "abc,abc,abc,NewYork",
        country: "USA",
      },
    ],
    yourProduct: [
      {
        id: "b1",
        category: ["featuredbook"],
        link: "https://bookland.dexignzone.com/xhtml/images/books/large/bigbook1.jpg",
        title: "A Heavy Lift",
        author: "Alan Walker",
        genre: "Business & Strategy",
        des: "The book is a practical guide to developing a winning business strategy. With real-world examples and actionable advice, this book covers essential elements for success in today's competitive business landscape.",
        price: "9.5",
        oldPrice: "12.0",
        discount: "20",
        quantity: "1",
      },
    ],
  },
];
export default users;
